---
# This should work regardless of unit path or service state
- name: "Check if {{ unit }} unit is present" # noqa command-instead-of-module
  command:
    cmd: "systemctl cat {{ unit }}"
  changed_when: false
  failed_when: false
  register: servicecheck_cat_unit

- set_fact:
    servicecheck:
      systemd: "{{ servicecheck.systemd }}"
      exists: true
      started: "{{ servicecheck.started }}"
  when: servicecheck_cat_unit.rc == 0

- include_tasks: started.yml
  when: servicecheck_cat_unit.rc == 0
