---
# Default values
- set_fact:
    servicecheck:
      systemd: false
      exists: false
      started: false

- name: Update apt cache
  apt:
    update_cache: true
  when: (ansible_os_family == 'Debian') and (servicecheck_installed_procps is not defined)

- name: Install ps
  package:
    name: "procps{% if ansible_os_family == 'RedHat' %}-ng{% endif %}"
    state: latest
  register: servicecheck_installed_procps
  when: servicecheck_installed_procps is not defined

- name: Check if system is booted with systemd
  command:
    cmd: ps --no-headers -o comm 1
  changed_when: false
  register: servicecheck_pidone

# This is a more readable way to do it, but won't scale, so leave it.
#- set_fact:
#    servicecheck:
#      systemd: true
#      exists: "{{ servicecheck.exists }}"
#      started: "{{ servicecheck.started }}"

- set_fact:
    servicecheck: "{{ servicecheck | combine({'systemd': true}) }}"
  when: servicecheck_pidone.stdout == 'systemd'

- include_tasks: exists.yml
  when: servicecheck_pidone.stdout == 'systemd'
